'use client';

import { tv } from 'tailwind-variants';

export const buttonVariants = tv({
  base: [
    'inline-flex items-center justify-center gap-2',
    'whitespace-nowrap rounded-md text-sm font-semibold',
    'transition-colors duration-200 ease-in-out',
    'focus-visible:outline-none focus-visible:ring-2',
    'focus-visible:ring-ring focus-visible:ring-inset',
    'disabled:pointer-events-none disabled:opacity-50',
    '[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0',
  ],
  defaultVariants: {
    intent: 'default',
    size: 'md',
    variant: 'outline',
  },
  variants: {
    intent: {
      cautionary: [
        'data-[variant=outline]:border-cautionary data-[variant=outline]:text-cautionary',
        'data-[variant=outline]:hover:bg-cautionary data-[variant=outline]:hover:text-cautionary-foreground',
        'data-[variant=solid]:border-cautionary data-[variant=solid]:bg-cautionary data-[variant=solid]:text-cautionary-foreground',
        'data-[variant=solid]:hover:bg-cautionary',
        'data-[variant=ghost]:text-cautionary data-[variant=ghost]:hover:bg-cautionary/20',
        'data-[variant=link]:text-cautionary',
        'focus-visible:ring-cautionary',
      ],
      default: [
        'data-[variant=outline]:border-input data-[variant=outline]:text-font-primary',
        'data-[variant=outline]:hover:bg-primary/80 data-[variant=outline]:hover:border-primary data-[variant=outline]:hover:text-primary-foreground',
        'data-[variant=solid]:border-input data-[variant=solid]:bg-background data-[variant=solid]:text-font-secondary',
        'data-[variant=solid]:hover:border-primary data-[variant=solid]:hover:bg-primary data-[variant=solid]:hover:text-primary-foreground',
        'data-[variant=ghost]:text-font-primary data-[variant=ghost]:hover:bg-background/15',
        'data-[variant=link]:text-font-primary',
        'focus-visible:ring-primary',
      ],
      destructive: [
        'data-[variant=outline]:border-destructive data-[variant=outline]:text-destructive',
        'data-[variant=outline]:hover:bg-destructive data-[variant=outline]:hover:text-destructive-foreground',
        'data-[variant=solid]:border-destructive data-[variant=solid]:bg-destructive data-[variant=solid]:text-destructive-foreground',
        'data-[variant=solid]:hover:bg-destructive',
        'data-[variant=ghost]:text-destructive data-[variant=ghost]:hover:bg-destructive/20',
        'data-[variant=link]:text-destructive',
        'focus-visible:ring-destructive',
      ],
      informative: [
        'data-[variant=outline]:border-informative data-[variant=outline]:text-informative',
        'data-[variant=outline]:hover:bg-informative data-[variant=outline]:hover:text-informative-foreground',
        'data-[variant=solid]:border-informative data-[variant=solid]:bg-informative data-[variant=solid]:text-informative-foreground',
        'data-[variant=solid]:hover:bg-informative',
        'data-[variant=ghost]:text-informative data-[variant=ghost]:hover:bg-informative/20',
        'data-[variant=link]:text-informative',
        'focus-visible:ring-informative',
      ],
      negative: [
        'data-[variant=outline]:border-negative data-[variant=outline]:text-negative',
        'data-[variant=outline]:hover:bg-negative data-[variant=outline]:hover:text-negative-foreground',
        'data-[variant=solid]:border-negative data-[variant=solid]:bg-negative data-[variant=solid]:text-negative-foreground',
        'data-[variant=solid]:hover:bg-negative',
        'data-[variant=ghost]:text-negative data-[variant=ghost]:hover:bg-negative/20',
        'data-[variant=link]:text-negative',
        'focus-visible:ring-negative',
      ],
      positive: [
        'data-[variant=outline]:border-positive data-[variant=outline]:text-positive',
        'data-[variant=outline]:hover:bg-positive data-[variant=outline]:hover:text-positive-foreground',
        'data-[variant=solid]:border-positive data-[variant=solid]:bg-positive data-[variant=solid]:text-positive-foreground',
        'data-[variant=solid]:hover:bg-positive',
        'data-[variant=ghost]:text-positive data-[variant=ghost]:hover:bg-positive/20',
        'data-[variant=link]:text-positive',
        'focus-visible:ring-positive',
      ],
      primary: [
        'data-[variant=outline]:border-primary data-[variant=outline]:text-primary',
        'data-[variant=outline]:hover:bg-primary data-[variant=outline]:hover:text-primary-foreground',
        'data-[variant=solid]:border-primary data-[variant=solid]:bg-primary data-[variant=solid]:text-primary-foreground',
        'data-[variant=solid]:hover:bg-primary',
        'data-[variant=ghost]:text-primary data-[variant=ghost]:hover:bg-primary/20',
        'data-[variant=link]:text-primary',
        'focus-visible:ring-primary',
      ],
      secondary: [
        'data-[variant=outline]:border-secondary data-[variant=outline]:text-secondary',
        'data-[variant=outline]:hover:bg-secondary data-[variant=outline]:hover:text-secondary-foreground',
        'data-[variant=solid]:border-secondary data-[variant=solid]:bg-secondary data-[variant=solid]:text-secondary-foreground',
        'data-[variant=solid]:hover:bg-secondary',
        'data-[variant=ghost]:text-secondary data-[variant=ghost]:hover:bg-secondary/20',
        'data-[variant=link]:text-secondary',
        'focus-visible:ring-secondary',
      ],
      tertiary: [
        'data-[variant=outline]:border-tertiary data-[variant=outline]:text-tertiary',
        'data-[variant=outline]:hover:bg-tertiary data-[variant=outline]:hover:text-tertiary-foreground',
        'data-[variant=solid]:border-tertiary data-[variant=solid]:bg-tertiary data-[variant=solid]:text-tertiary-foreground',
        'data-[variant=solid]:hover:bg-tertiary',
        'data-[variant=ghost]:text-tertiary data-[variant=ghost]:hover:bg-tertiary/20',
        'data-[variant=link]:text-tertiary',
        'focus-visible:ring-tertiary',
      ],
    },
    size: {
      icon: 'size-5 rounded-full',
      lg: 'h-12 px-5 py-2',
      md: 'h-10 px-4 py-2',
      sm: 'h-8 px-3 py-2',
    },
    variant: {
      ghost: 'bg-transparent',
      link: 'bg-transparent underline-offset-4 hover:underline',
      outline: 'border bg-background',
      solid: 'border',
    },
  },
});
